# Generated by Django 5.1.4 on 2024-12-11 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='kathmandu', max_length=255, verbose_name='District Name (English)')),
                ('name_ne', models.CharField(default='kathmandu', max_length=255, verbose_name='District Name (Nepali)')),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='bagmati', max_length=255, unique=True, verbose_name='Province Name (English)')),
                ('name_ne', models.CharField(default='bagmati', max_length=255, unique=True, verbose_name='Province Name (Nepali)')),
            ],
            options={
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='kathmandu', max_length=255, verbose_name='Municipality Name (English)')),
                ('name_ne', models.CharField(default='kathmandu', max_length=255, verbose_name='Municipality Name (Nepali)')),
                ('lg_code', models.CharField(default=1001, max_length=255, verbose_name='Local Government Code')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='federal.district')),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'unique_together': {('name_en', 'district')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='federal.province'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name_en', 'province')},
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.PositiveIntegerField(default=1, verbose_name='Ward Number')),
                ('name_en', models.CharField(default=1, max_length=255, verbose_name='Ward Name (English)')),
                ('name_ne', models.CharField(default=1, max_length=255, verbose_name='Ward Name (Nepali)')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='federal.municipality')),
            ],
            options={
                'verbose_name_plural': 'Wards',
                'unique_together': {('ward_number', 'municipality')},
            },
        ),
    ]
