# Generated by Django 5.1.4 on 2024-12-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsector_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SubSectors',
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_level', models.IntegerField(choices=[(2, 'Municipality'), (1, 'Ward')], default=1)),
                ('budgetsubhead', models.CharField(blank=True, max_length=255, null=True)),
                ('programnamenp', models.CharField(blank=True, max_length=255, null=True)),
                ('fiscal_year', models.CharField(choices=[('79-80', '79-80'), ('80-81', '80-81'), ('81-82', '81-82')], default='79-80', max_length=50)),
                ('fund_type', models.CharField(choices=[('1', 'CAPITAL'), ('2', 'RECURRENT'), ('3', 'FINANCING')], default='1', max_length=50)),
                ('economic_code', models.IntegerField(default=2000)),
                ('economic_code_name', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cofog', models.IntegerField(default=100000)),
                ('cofog_name', models.CharField(blank=True, max_length=50, null=True)),
                ('source_level', models.CharField(blank=True, max_length=50, null=True)),
                ('source_name', models.CharField(blank=True, max_length=50, null=True)),
                ('revenue_item', models.CharField(blank=True, max_length=50, null=True)),
                ('support_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expenditure_amount', models.IntegerField(default=100000)),
                ('description', models.TextField(blank=True, null=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipality_allocations', to='federal.municipality')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_allocations', to='federal.ward')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='budget_analysis.sector')),
                ('sub_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsector', to='budget_analysis.subsector')),
            ],
        ),
    ]
